lib <- file.path("build", "library")
if (dir.exists(lib)) .libPaths(c(normalizePath(lib), .libPaths()))
Sys.setenv(R_LIBS = paste(.libPaths(), collapse = .Platform$path.sep))
pkgdown::init_site()
source("tools/coverage.R")
pkgdown::build_site(new_process = FALSE, install = TRUE, preview = FALSE)
