name: Test

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
  pull_request:
  workflow_dispatch:
    inputs:
      ref:
        description: Git branch, tag, or commit to test
        required: false
        type: string
  workflow_call:
    inputs:
      ref:
        description: Git branch, tag, or commit to test
        required: false
        type: string

permissions:
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v7.0.1
        with:
          ref: ${{ inputs.ref || github.sha }}

      - name: Set up R
        uses: r-lib/actions/setup-r@v2.12.1
        with:
          r-version: release
          use-public-rspm: true

      - name: Install coverage dependencies
        uses: r-lib/actions/setup-r-dependencies@v2.12.1
        with:
          extra-packages: |
            any::covr
            any::xml2
            local::.
          needs: coverage

      - name: Generate coverage reports
        shell: Rscript {0}
        run: source("tools/coverage.R")

      - name: Store coverage reports
        uses: actions/upload-artifact@v7.0.1
        with:
          name: coverage-report
          path: docs/coverage/

      - name: Upload coverage to Codecov
        if: env.CODECOV_TOKEN != ''
        uses: codecov/codecov-action@v7.0.0
        with:
          token: ${{ env.CODECOV_TOKEN }}
          slug: ultreia-io/ros.form
          files: docs/coverage/coverage.xml
          disable_search: true
          fail_ci_if_error: true
